<?php

/**
 * Administrateur
 */

use Epiclub\Domain\UtilisateurManager;

$admin = [
    'nom' => 'Doe',
    'prenom' => 'John',
    'username' => 'JohnDoe',
    'email' => 'johndoe@test.tld',
    'password' => ''
];
$form_errors = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    /** @todo Need form validation here */

    if (empty($form_errors)) {
        $admin = [
            'nom' => $_POST['nom'], 
            'prenom' => $_POST['prenom'], 
            'username' => $_POST['username'], 
            'email' => $_POST['email'], 
            'password' => password_hash($_POST['password'], PASSWORD_DEFAULT)
        ];
        $admin['role'] = 'ROLE_ADMIN';
        $admin['date_creation'] = (new DateTime())->format('Y-m-d h:m:s');
        $admin['derniere_connexion'] = null;

        $utilisateurManager = new UtilisateurManager();
        $utilisateurManager->save($admin);

        // ⬇️⬇️⬇️ NOUVEAU : Génération de la clé de chiffrement ⬇️⬇️⬇️
        
        // 1. Générer une clé aléatoire de 32 octets (256 bits) en hexadécimal
        $keyHex = bin2hex(random_bytes(32));
        
        // 2. Définir le chemin vers le fichier .env.local.php (à la racine du projet)
        $envFilePath = __DIR__ . '/../../.env.local.php';
        
        // 3. Charger le contenu existant ou créer un tableau de base
        if (file_exists($envFilePath)) {
            $config = include $envFilePath;
            if (!is_array($config)) {
                $config = [];
            }
        } else {
            $config = [];
        }
        
        // 4. Ajouter ou mettre à jour les clés de configuration
        $config['SECRET_KEY'] = $keyHex;
        $config['CIPHER_METHOD'] = 'AES-256-CBC';
        
        // 5. Écrire le fichier .env.local.php
        $content = "<?php\n\n/**\n * This file is autogenerated by application.\n * Do not edit manually.\n */\nreturn " . var_export($config, true) . ";\n";
        
        if (file_put_contents($envFilePath, $content) === false) {
            // Si l'écriture échoue, on affiche une erreur mais on continue quand même
            // (l'admin pourra générer la clé manuellement plus tard)
            $keyGenerated = false;
        } else {
            $keyGenerated = true;
        }
        
        // ⬆️⬆️⬆️ FIN DE L'AJOUT ⬆️⬆️⬆️

        // save admin params
        header("Location: ?step=club");
        exit();
    }
}

?>

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Epiclub</title>
    <link rel="shortcut icon" href="/assets/img/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="/assets/css/cosmo.min.css">
</head>

<body>
    <div class="container">
        <h1>Epiclub | Nouvelle installation</h1>
        <hr>
        <form method="post">
            <h2>Administrateur</h2>
            <?php if (isset($keyGenerated) && $keyGenerated): ?>
                <div class="alert alert-success">
                    ✅ Clé de chiffrement générée et stockée dans <strong>.env.local.php</strong>
                </div>
            <?php elseif (isset($keyGenerated) && !$keyGenerated): ?>
                <div class="alert alert-warning">
                    ⚠️ Impossible d'écrire le fichier <strong>.env.local.php</strong>.<br>
                    Veuillez générer manuellement une clé :<br>
                    <code>php -r "echo bin2hex(random_bytes(32));"</code><br>
                    Et ajoutez-la dans <strong>.env.local.php</strong> avec les clés :<br>
                    <code>'SECRET_KEY' => 'la_clé_générée',</code><br>
                    <code>'CIPHER_METHOD' => 'AES-256-CBC',</code>
                </div>
            <?php endif; ?>
            <div class="mb-3">
                <label for="nom">Nom</label>
                <input type="text" class="form-control" name="nom" id="nom" value="<?= htmlspecialchars($admin['nom']); ?>" required>
            </div>
            <div class="mb-3">
                <label for="prenom">Prénom</label>
                <input type="text" class="form-control" name="prenom" id="prenom" value="<?= htmlspecialchars($admin['prenom']); ?>" required>
            </div>
            <div class="mb-3">
                <label for="username">Nom d'utilisateur</label>
                <input type="text" class="form-control" name="username" id="username" value="<?= htmlspecialchars($admin['username']); ?>" required>
            </div>
            <div class="mb-3">
                <label for="email">Adresse mail</label>
                <input type="email" class="form-control" name="email" id="email" value="<?= htmlspecialchars($admin['email']); ?>" required>
            </div>
            <div class="mb-3">
                <label for="password">Mot de passe</label>
                <input type="password" class="form-control" name="password" id="password" required>
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Valider</button>
            </div>
        </form>
    </div>
</body>

</html>