<?php

/**
 * Administrateur
 */

use Epiclub\Domain\UtilisateurManager;

$admin = [
    'nom' => '',
    'prenom' => '',
    'username' => '',
    'email' => '',
];
$form_errors = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Validation
    if (empty($_POST['nom'])) { $form_errors[] = 'Le nom est requis.'; }
    if (empty($_POST['prenom'])) { $form_errors[] = 'Le prénom est requis.'; }
    if (empty($_POST['username'])) { $form_errors[] = 'Le nom d\'utilisateur est requis.'; }
    if (empty($_POST['email']) || !filter_var($_POST['email'], FILTER_VALIDATE_EMAIL)) {
        $form_errors[] = 'Une adresse email valide est requise.';
    }
    if (empty($_POST['password']) || strlen($_POST['password']) < 12) {
        $form_errors[] = 'Le mot de passe doit contenir au moins 12 caractères.';
    }
    if (($_POST['password'] ?? '') !== ($_POST['password_confirm'] ?? '')) {
        $form_errors[] = 'Les deux mots de passe ne correspondent pas.';
    }

    if (empty($form_errors)) {
        $admin = [
            'nom' => $_POST['nom'],
            'prenom' => $_POST['prenom'],
            'username' => $_POST['username'],
            'email' => $_POST['email'],
            'password' => password_hash($_POST['password'], PASSWORD_DEFAULT)
        ];
        $admin['role'] = 'ROLE_ADMIN';
        $admin['date_creation'] = (new DateTime())->format('Y-m-d H:i:s');
        $admin['derniere_connexion'] = null;
        $admin['last_activity'] = null;
        $admin['reset_token'] = null;
        $admin['reset_token_expires'] = null;
        $admin['reset_email_sent_at'] = null;
        $admin['controle_en_cours_id'] = null;

        $utilisateurManager = new UtilisateurManager();
        $utilisateurManager->save($admin);

        // Génération de la clé de chiffrement
        $keyHex = bin2hex(random_bytes(32));
        $envFilePath = __DIR__ . '/../../.env.local.php';
        if (file_exists($envFilePath)) {
            $config = include $envFilePath;
            if (!is_array($config)) {
                $config = [];
            }
        } else {
            $config = [];
        }
        $config['SECRET_KEY'] = $keyHex;
        $config['CIPHER_METHOD'] = 'AES-256-CBC';
        $content = "<?php\n\n/**\n * This file is autogenerated by application.\n * Do not edit manually.\n */\nreturn " . var_export($config, true) . ";\n";
        $keyGenerated = (file_put_contents($envFilePath, $content) !== false);

        header('Location: ?step=smtp');
        exit();
    }
}

require __DIR__ . '/../includes/header.php';
?>

<h1>Administrateur</h1>
<hr>

<p class="text-muted">
    Créez le compte super administrateur. Ce compte aura tous les droits.
    Choisissez un mot de passe robuste et unique.
</p>

<?php if (!empty($form_errors)): ?>
    <div class="alert alert-danger">
        <ul>
            <?php foreach ($form_errors as $error): ?>
                <li><?= htmlspecialchars($error) ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<?php if (isset($keyGenerated) && $keyGenerated): ?>
    <div class="alert alert-success">
        ✅ Clé de chiffrement générée et stockée dans <strong>.env.local.php</strong>
    </div>
<?php elseif (isset($keyGenerated) && !$keyGenerated): ?>
    <div class="alert alert-warning">
        ⚠️ Impossible d'écrire le fichier <strong>.env.local.php</strong>.<br>
        Veuillez générer manuellement une clé :<br>
        <code>php -r "echo bin2hex(random_bytes(32));"</code><br>
        Et ajoutez-la dans <strong>.env.local.php</strong> avec les clés :<br>
        <code>'SECRET_KEY' => 'la_clé_générée',</code><br>
        <code>'CIPHER_METHOD' => 'AES-256-CBC',</code>
    </div>
<?php endif; ?>

<form method="post">
    <div class="mb-3">
        <label for="nom" class="form-label">Nom</label>
        <input type="text" class="form-control" name="nom" id="nom" value="<?= htmlspecialchars($admin['nom']); ?>" required>
    </div>
    <div class="mb-3">
        <label for="prenom" class="form-label">Prénom</label>
        <input type="text" class="form-control" name="prenom" id="prenom" value="<?= htmlspecialchars($admin['prenom']); ?>" required>
    </div>
    <div class="mb-3">
        <label for="username" class="form-label">Nom d'utilisateur</label>
        <input type="text" class="form-control" name="username" id="username" value="<?= htmlspecialchars($admin['username']); ?>" required>
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Adresse mail</label>
        <input type="email" class="form-control" name="email" id="email" value="<?= htmlspecialchars($admin['email']); ?>" required>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Mot de passe</label>
        <input type="password" class="form-control" name="password" id="password" minlength="12" required>
        <small class="text-muted">12 caractères minimum.</small>
    </div>
    <div class="mb-3">
        <label for="password_confirm" class="form-label">Confirmer le mot de passe</label>
        <input type="password" class="form-control" name="password_confirm" id="password_confirm" minlength="12" required>
    </div>
    <button type="submit" class="btn btn-primary">Valider</button>
</form>

<?php require __DIR__ . '/../includes/footer.php'; ?>