<?php

namespace Epiclub\Engine;

class EnvironmentFileParser
{
    private array $env = [];

    public function __construct()
    {
        if (file_exists(__DIR__ . '/../../.env.local.php')) {
            $this->env = require(__DIR__ . '/../../.env.local.php');
        }
    }

    public function set($key, $value)
    {
        $this->env[strtoupper($key)] = $value;
        $this->_dump();
    }

    private function _dump()
    {
        $file = fopen(__DIR__ . '/../../.env.local.php', "wb");

        if (!$file) {
            throw new \Exception("Unable to create environment file.", 1);
        }

        fputs($file, "<?php\n\n");
        fputs($file, "/**\n");
        fputs($file, " * This file is autogenerated by application.\n");
        fputs($file, " * Do not edit manually.\n");
        fputs($file, " */\n");
        fputs($file, "return [\n");
        foreach ($this->env as $key => $value) {
            fputs($file, "    '$key' => '$value',\n");
        }
        fputs($file, "];\n");
        fclose($file);
    }
}
