<?php

namespace Epiclub\Engine;

class EnvironmentFileParser
{
    private array $env = [];
    private string $filePath;

    /**
     * @param string|null $filePath Chemin du fichier .env.local.php.
     *                              Défaut : {app/Engine}/../../.env.local.php
     *                              (chemin historique, conservé pour
     *                              iso-comportement). Le paramètre est
     *                              injectable pour les tests.
     */
    public function __construct(?string $filePath = null)
    {
        $this->filePath = $filePath ?? __DIR__ . '/../../.env.local.php';

        if (file_exists($this->filePath)) {
            $this->env = require($this->filePath);
        }
    }

    public function set($key, $value)
    {
        $this->env[strtoupper($key)] = $value;
        $this->_dump();
    }

    private function _dump()
    {
        $file = fopen($this->filePath, "wb");

        if (!$file) {
            throw new \Exception("Unable to create environment file.", 1);
        }

        fputs($file, "<?php\n\n");
        fputs($file, "/**\n");
        fputs($file, " * This file is autogenerated by application.\n");
        fputs($file, " * Do not edit manually.\n");
        fputs($file, " */\n");
        fputs($file, "return [\n");
        foreach ($this->env as $key => $value) {
            fputs($file, "    '$key' => '$value',\n");
        }
        fputs($file, "];\n");
        fclose($file);
    }
}