<?php

use Epiclub\Controller\AppSetupController;

require __DIR__ . '/../vendor/autoload.php';

$envFile = __DIR__ . '/../.env.local.php';
$config = file_exists($envFile) ? (include $envFile) : [];
if (!is_array($config)) {
    $config = [];
}

// L'installation est considérée terminée si :
//  - SETUP_COMPLETE est explicitement posé, OU
//  - les paramètres DB sont présents ET un utilisateur existe déjà en base
$setupComplete = !empty($config['SETUP_COMPLETE']);

if (!$setupComplete && !empty($config['DB_HOST']) && !empty($config['DB_NAME'])) {
    // Fallback : détecter une installation existante sans flag SETUP_COMPLETE
    try {
        $pdo = new \PDO(
            'mysql:host=' . $config['DB_HOST']
            . ';dbname=' . $config['DB_NAME']
            . ';charset=utf8mb4',
            $config['DB_USER'],
            $config['DB_PASS'],
            [\PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION]
        );
        $count = (int) $pdo->query("SELECT COUNT(*) FROM utilisateur")->fetchColumn();
        if ($count > 0) {
            // Installation existante : on marque comme complète et on met à jour le fichier
            $config['SETUP_COMPLETE'] = true;
            $content = "<?php\n\n/**\n * This file is autogenerated by application.\n * Do not edit manually.\n */\nreturn " . var_export($config, true) . ";\n";
            @file_put_contents($envFile, $content);
            $setupComplete = true;
        }
    } catch (\Throwable $e) {
        // Table utilisateur absente ou DB inaccessible → on reste sur le setup
        error_log('[bootstrap] SETUP_COMPLETE fallback failed: ' . $e->getMessage());
    }
}

if (!$setupComplete) {
    if (is_dir(__DIR__ . '/../setup')) {
        require __DIR__ . '/../setup/install.php';
        exit();
    }
    http_response_code(503);
    exit("EPIClub n'est pas installé. Consultez la documentation.");
}

$_ENV = $config;
require __DIR__ . '/../ressources/routes.php';

if (isset($_ENV['APP_ENV']) && $_ENV['APP_ENV'] === 'dev') {
    error_reporting(E_ALL);

    function dd(mixed $variable, $exit = true)
    {
        echo '<pre>';
        var_dump($variable);
        echo '</pre>';
        if ($exit) {
            exit();
        }
    }
}