<?php

namespace Epiclub\Controller;

use Epiclub\Engine\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;

class IndexController extends AbstractController
{
    public function index(Request $request): Response
    {
        return $this->redirectTo('/tableau_de_bord');
    }

    public function dashboard(Request $request): Response
    {
        return $this->render('tableau_de_bord.twig', []);
    }
    
    public function systemSettings(Request $request): Response
    {
        // Vérification des droits admin (si nécessaire)
        // if (!$this->isAdmin()) { return $this->redirectTo('/'); }
        
        // Lecture des paramètres actuels depuis .env.local.php
        $mailerDsn = getenv('MAILER_DSN') ?: $_ENV['MAILER_DSN'] ?? '';
        $mailerFrom = getenv('MAILER_FROM') ?: $_ENV['MAILER_FROM'] ?? '';
        $mailerName = getenv('MAILER_NAME') ?: $_ENV['MAILER_NAME'] ?? '';
        
        $dsnParts = parse_url($mailerDsn);
        $smtpHost = $dsnParts['host'] ?? '';
        $smtpPort = $dsnParts['port'] ?? 25;
        $smtpUser = $dsnParts['user'] ?? '';
        $smtpPass = urldecode($dsnParts['pass'] ?? '');
        parse_str($dsnParts['query'] ?? '', $query);
        $smtpEncryption = $query['encryption'] ?? '';
        
        return $this->render('system_settings.twig', [
            'settings' => [
                'smtp_host' => $smtpHost,
                'smtp_port' => $smtpPort,
                'smtp_username' => $smtpUser,
                'smtp_password' => $smtpPass,
                'smtp_encryption' => $smtpEncryption,
                'mail_from' => $mailerFrom,
                'mail_from_name' => $mailerName,
            ]
        ]);
    }
    
    /**
    * @Route("/update-smtp", name="update_smtp", methods={"POST"})
    */
    public function updateSmtp(Request $request): Response
    {
        // Récupération des données du formulaire
        $host = $request->request->get('smtp_host');
        $port = $request->request->get('smtp_port');
        $user = $request->request->get('smtp_username');
        $pass = $request->request->get('smtp_password');
        $encryption = $request->request->get('smtp_encryption');
        $from = $request->request->get('mail_from');
        $fromName = $request->request->get('mail_from_name');
        
        // Validation basique
        if (empty($host) || empty($port) || empty($user) || empty($from)) {
            // Rediriger avec un message d'erreur (vous pouvez utiliser des sessions)
            return $this->redirectTo('/tableau_de_bord?error=missing_fields');
        }
        
        // Encoder le mot de passe pour l'URL (si il contient des caractères spéciaux comme @)
        $passEncoded = urlencode($pass);
        
        // Construire le nouveau DSN
        $dsn = sprintf('smtp://%s:%s@%s:%s',
            $user,
            $passEncoded,
            $host,
            $port
        );
        if ($encryption && $encryption !== 'none') {
            $dsn .= '?encryption=' . $encryption;
        }
        
        // Lire le fichier .env.local.php actuel
        $envFile = __DIR__ . '/../../.env.local.php'; // ajustez le chemin si nécessaire
        if (!file_exists($envFile)) {
            return $this->redirectTo('/tableau_de_bord?error=env_file_not_found');
        }
        
        $current = require $envFile;
        if (!is_array($current)) {
            return $this->redirectTo('/tableau_de_bord?error=invalid_env');
        }
        
        // Mettre à jour les clés
        $current['MAILER_DSN'] = $dsn;
        $current['MAILER_FROM'] = $from;
        $current['MAILER_NAME'] = $fromName;
        
        // Réécrire le fichier
        $content = '<?php' . "\n\n";
        $content .= '/**' . "\n";
        $content .= ' * This file is autogenerated by application.' . "\n";
        $content .= ' * Do not edit manually.' . "\n";
        $content .= ' */' . "\n";
        $content .= 'return ' . var_export($current, true) . ';' . "\n";
        
        // Écrire le fichier
        file_put_contents($envFile, $content);
        
        // Rediriger vers le tableau de bord avec un message de succès
        return $this->redirectTo('/tableau_de_bord?success=1');
    }
    
    /**
    * Envoie un email de test pour vérifier la configuration SMTP
    */
    // Dans la classe IndexController, remplacez ou ajoutez cette méthode :
    public function testMail(Request $request): Response
    {
        try {
            // Charger .env.local.php
            $envFile = __DIR__ . '/../../.env.local.php';
            if (!file_exists($envFile)) {
                return new JsonResponse(['success' => false, 'error' => 'Fichier .env.local.php introuvable']);
            }
            $env = require $envFile;
            $from = $env['MAILER_FROM'] ?? '';
            $fromName = $env['MAILER_NAME'] ?? 'EPIClub';
            $dsn = $env['MAILER_DSN'] ?? '';
            
            if (empty($from) || empty($dsn)) {
                return new JsonResponse(['success' => false, 'error' => 'Adresse expéditeur ou DSN manquant dans .env.local.php']);
            }
            
            // Instancier le service mailer
            $mailer = new \Epiclub\Engine\MailerService($dsn);
            
            // Créer l'email de test
            $email = new \Symfony\Component\Mime\Email();
            // Format valide : "Nom <email>"
            $email->from($fromName . ' <' . $from . '>')
            ->to($from)
            ->subject('[TEST] Configuration SMTP EPIClub')
            ->text("Ceci est un email de test.\n\nSi vous recevez ce message, votre configuration SMTP est correcte.\n\nDate : " . date('d/m/Y H:i:s'));
            
            $mailer->sendEmail($email);
            
            return new JsonResponse([
                'success' => true,
                'message' => '✅ Email de test envoyé avec succès à ' . $from
            ]);
            
        } catch (\Exception $e) {
            return new JsonResponse([
                'success' => false,
                'error' => 'Erreur lors de l\'envoi : ' . $e->getMessage()
            ], 500);
        }
    }

}
    