<?php

namespace Epiclub\Engine;

class EnvironmentFileParser
{
    private array $env = [];
    private string $filePath;

    public function __construct()
    {
        $this->filePath = __DIR__ . '/../../.env.local.php';
        
        if (file_exists($this->filePath)) {
            $this->env = require($this->filePath);
        }
    }

    public function set($key, $value)
    {
        $this->env[strtoupper($key)] = $value;
        $this->_dump();
    }

    public function get($key, $default = null)
    {
        return $this->env[strtoupper($key)] ?? $default;
    }

    /**
     * Charge le fichier de configuration et retourne son contenu
     */
    public function load()
    {
        if (file_exists($this->filePath)) {
            $this->env = require($this->filePath);
        }
        return $this->env;
    }

    /**
     * Sauvegarde les modifications dans le fichier
     */
    public function save()
    {
        $this->_dump();
    }

    /**
     * Retourne toutes les données de l'environnement
     */
    public function all()
    {
        return $this->env;
    }

    private function _dump()
    {
        $file = fopen($this->filePath, "wb");

        if (!$file) {
            throw new \Exception("Unable to create environment file.", 1);
        }

        fputs($file, "<?php\n\n");
        fputs($file, "/**\n");
        fputs($file, " * This file is autogenerated by application.\n");
        fputs($file, " * Do not edit manually.\n");
        fputs($file, " */\n");
        fputs($file, "return [\n");
        foreach ($this->env as $key => $value) {
            fputs($file, "    '$key' => '$value',\n");
        }
        fputs($file, "];\n");
        fclose($file);
    }
}